version: "3.7"
networks:
  use:
    external: false # Create the volume if it doesn't exist
    name: use_network
    driver: bridge
volumes:
  data:

services:
  master:
    container_name: master
    restart: unless-stopped
    image: elastic/all-in-one
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "80:80"
      - "443:443"
      - "5601:5601"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ES_HEAP_SIZE=2g
      - RUNNING_MODE=all # can be master, ingest, data, kibana, logstash, elasticsearch, all
      - SSL=true # can also be false
    volumes:
      - data:/usr/share/elasticsearch/data
      - ./config/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - use
